# Project: StrongHolder(BE)
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = StrongHolder(BE)_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib" -L"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = StrongHolder(BE).exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

StrongHolder(BE)_private.res: StrongHolder(BE)_private.rc 
	$(WINDRES) -i StrongHolder(BE)_private.rc --input-format=rc -o StrongHolder(BE)_private.res -O coff 

